name: Trivy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    name: Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Trivy scan
        id: trivy-scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # 0.36.0
        with:
          scan-type: config
          scan-ref: .
          format: sarif
          trivyignores: .github/.trivyignore.yml
          output: trivy-results.sarif

      - name: Upload Trivy SARIF results
        id: upload-sarif
        uses: github/codeql-action/upload-sarif@9e0d7b8d25671d64c341c19c0152d693099fb5ba # v4.35.5
        if: always()
        with:
          sarif_file: trivy-results.sarif
